module.exports = {
  compilerOptions: {
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "alwaysStrict": true,
    "checkJs": false,
    "declaration": true,
    "declarationMap": false,
    "declarationDir": './dist/types',
    "exactOptionalPropertyTypes": true,
    "isolatedModules": false,
    "lib": ['dom', 'dom.iterable', 'esnext'],
    "module": "esnext",
    "noEmit": false,
    "noEmitOnError": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": './dist',
    "removeComments": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "strictNullChecks": true,
    "target": "esnext",
    "typeRoots": ['./dist/types'],
    "useUnknownInCatchVariables": true
  },
  include: ['src'],
  exclude: ['node_modules', 'src/*.test.ts', 'src/*.test.tsx', 'src/__mocks__'],
}
