module.exports = {
  compilerOptions: {
    allowJs: false,
    allowSyntheticDefaultImports: true,
    alwaysStrict: true,
    checkJs: true,
    declaration: true,
    module: 'es2020',
    moduleResolution: 'node',
    noEmit: false,
    noFallthroughCasesInSwitch: true,
    noImplicitAny: true,
    noImplicitReturns: true,
    noUnusedLocals: true,
    noUnusedParameters: true,
    outDir: './dist',
    skipLibCheck: true,
    sourceMap: true,
    strict: true,
    target: 'es2020',
  },
  include: ['src'],
  exclude: ['node_modules', 'src/*.test.ts', 'src/*.test.tsx', 'src/__mocks__'],
}
